// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lufikdbibkoaqymjvecj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imx1ZmlrZGJpYmtvYXF5bWp2ZWNqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM3NDY5MjUsImV4cCI6MjA2OTMyMjkyNX0.ZyV79YR7PogJOo08NEjd2FkRBqgIl28gNzb7aMQG_xw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});